In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Names_dataset.csv")

In [4]:
df

name gender
0           alfiya      f
1           ardwin      m
2          henryka      f
3           preeti      f
4           jamaro      m
...            ...    ...
125226    loreatha      f
125227       deepa      f
125228    kinshasa      f
125229  charlianne      f
125230      ashish      m

[125231 rows x 2 columns]

In [5]:
df.describe()

name  gender
count   125175  125231
unique  108568       2
top      pooja       f
freq       357   75971

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125231 entries, 0 to 125230
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   name    125175 non-null  object
 1   gender  125231 non-null  object
dtypes: object(2)
memory usage: 1.9+ MB


In [7]:
df.count()

name      125175
gender    125231
dtype: int64

In [10]:
df.head()

name gender
0   alfiya      f
1   ardwin      m
2  henryka      f
3   preeti      f
4   jamaro      m

In [11]:
df.tail(10)

name gender
125221        major      m
125222      chazten      m
125223  pawan kumar      m
125224     dalshawn      m
125225      hillary      m
125226     loreatha      f
125227        deepa      f
125228     kinshasa      f
125229   charlianne      f
125230       ashish      m

In [12]:
gender = {'m':1,'f':0}
df.gender = [gender[item] for item in df.gender]

In [13]:
df

name  gender
0           alfiya       0
1           ardwin       1
2          henryka       0
3           preeti       0
4           jamaro       1
...            ...     ...
125226    loreatha       0
125227       deepa       0
125228    kinshasa       0
125229  charlianne       0
125230      ashish       1

[125231 rows x 2 columns]

In [15]:
df.size

250462

In [16]:
#for randomness we use dffinal = df.sample(frac=1)

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [18]:
names = df['name']

In [19]:
names

0             alfiya
1             ardwin
2            henryka
3             preeti
4             jamaro
             ...    
125226      loreatha
125227         deepa
125228      kinshasa
125229    charlianne
125230        ashish
Name: name, Length: 125231, dtype: object

In [20]:
names[0]

'alfiya'

In [21]:
cv = CountVectorizer()
x = cv.fit_transform(names.values.astype('U'))

In [22]:
cv.get_feature_names()

C:\Users\vimat\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aaban',
 'aabha',
 'aabid',
 'aabriella',
 'aachal',
 'aada',
 'aadam',
 'aadan',
 'aadarsh',
 'aaden',
 'aadesh',
 'aadhav',
 'aadhavan',
 'aadhi',
 'aadhira',
 'aadhvik',
 'aadhya',
 'aadhyan',
 'aadi',
 'aadian',
 'aadil',
 'aadin',
 'aadish',
 'aadison',
 'aadit',
 'aadith',
 'aadithya',
 'aaditri',
 'aaditya',
 'aadiv',
 'aadon',
 'aadrian',
 'aadrika',
 'aadrit',
 'aadvik',
 'aadvika',
 'aadya',
 'aadyn',
 'aaenab',
 'aafia',
 'aafreen',
 'aafrin',
 'aaftaab',
 'aaftab',
 'aagad',
 'aagam',
 'aagand',
 'aage',
 'aagot',
 'aahaan',
 'aahan',
 'aahana',
 'aahil',
 'aahim',
 'aahir',
 'aahliyah',
 'aahna',
 'aahron',
 'aahuja',
 'aaidan',
 'aaiden',
 'aaidyn',
 'aaila',
 'aailiyah',
 'aailyah',
 'aaima',
 'aaira',
 'aairah',
 'aaisha',
 'aaishah',
 'aaiyana',
 'aaiza',
 'aaja',
 'aajad',
 'aajah',
 'aajam',
 'aajaylah',
 'aajiv',
 'aajon',
 'aakanksha',
 'aakar',
 'aakarsh',
 'aakas',
 'aakash',
 'aakashmultan',
 'aakeem',
 'aakhon',
 'aakib',
 'aakil',
 'aakilah',
 'aakira',
 'aa

In [23]:
y = df.gender

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state = 42)

In [41]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [42]:
model.score(x_test,y_test)

0.7095603358579137

In [54]:
sample = ["vimath kumar"]
vector = cv.transform(sample).toarray()
model.predict(vector)

array([1], dtype=int64)

In [44]:
sample = ["sai"]
vector = cv.transform(sample).toarray()
model.predict(vector)

array([1], dtype=int64)

In [49]:
sample = ["joy"]
vector = cv.transform(sample).toarray()
model.predict(vector)

array([1], dtype=int64)

In [52]:
sample = ["priya"]
vector = cv.transform(sample).toarray()
model.predict(vector)

array([0], dtype=int64)

In [47]:
sample = ["smauel"]
vector = cv.transform(sample).toarray()
model.predict(vector)

array([1], dtype=int64)